name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀 on branch ${{ github.ref_name }}
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: List all branches
        run: |
          git branch -l -r
      - run: echo "🍏 This job's status is ${{ job.status }}."



# on:
#   pull_request:
#     branches:
#     - main
#   push:
#     branches:
#     - release/*
# jobs:
#   deploy_site:
#     name: deploy to site branch
#     runs-on: ubuntu-22.04
#     steps:
#     - uses: 
#     - name: use Node
#     - name: npm install, build, deploy
#     run: |
#       npm install
#       npm run build
#       git checkout deployment
#       git add out/
#       git commit "deployment on ${{ date }}"
#       git push
